FROM node:22.14.0-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache dumb-init python3 make g++

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci --frozen-lockfile
RUN npx prisma generate

COPY . .
RUN npm run build

EXPOSE 4000

ENTRYPOINT ["dumb-init", "--"]
CMD ["sh", "-c", "npx prisma migrate deploy && npm run start:dev"]
